--TARIH FONKSIYONLARI

--GETDATE : Bugunun tarihini verir.
SELECT GETDATE()

--DATEDIFF : Iki tarih arasinda gunu,ayi veya yili hesaplar
SELECT DATEDIFF(DAY,'05.09.1992',GETDATE())
SELECT DATEDIFF(MONTH, '05.09.1992',GETDATE())
SELECT DATEDIFF(YEAR, '05.09.1992',GETDATE())